### PR TITLE
Update MerlinAU.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Various code improvements & minor cleanup.

### CODE REVIEW

**Review by Firetop — APPROVED** [review]

**Review by Firetop — APPROVED** [review]

**Review by Firetop — APPROVED** [review]

**Comment by Firetop** [comment]
Some of the changes you made kinda clash with the changes I made in the dev branch already but that's okay because yours is easier to read than mine most of the time for the same change more or less lol.

Should we use dev moving forwards? was this just to cleanup main/master?

**Comment by Martinski4GitHub** [comment]
> Some of the changes you made kinda clash with the changes I made in the dev branch already but that's okay because yours is easier to read than mine most of the time for the same change more or less lol.
> 
Ah sorry man, my apologies! I didn't realize that you had already created the "**dev**" branch in your repository. Tuesday after dinner, the family was watching a movie I didn't really care for, so I figured I had about 90 minutes to review & check out the changes you had made. As usual, I went to my personal forked repository to make sure the source files were in synch with yours and then grabbed the shell script. After reviewing & testing I found some minor issues and decided to fix them and also made some improvements & some cleanup. All this time not knowing that the "**dev**" branch was already there in your own repo. Again, my apologies for creating conflicts with your latest changes in the "**dev**" branch.

>
> Should we use dev moving forwards? was this just to cleanup main/master?
>
So yes absolutely, from now on we should use the "**dev**" branch for further code changes until such time when they're deemed ready to merge with the "**main**" branch (now to be considered the "**official**" stable version).

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Okay I'm starting to understand the flow with Dev. I merged my changes into main for now, but going forwards I'll be working out of Dev and doing pull/merge requests like yourself.
> 
> I didn't realize that I should be merging master into my dev branch after you made changes. (i.e. do the merge the other way round) before creating the PR.
> 
> Learning! Slowly. :) For now I just added my minor improves to your changes since yours was more valuable, mine was mostly for the logging directories and visual stuff.
>
Yep, it's all part of the learning process and having fun :>), while adding to our skill sets.

**Comment by Martinski4GitHub** [comment]
> 
> Buddy it's all good! I honestly figured thats what happened haha! ;) I didn't know what to do at the time, I should of remerged your changes into my dev the other way around, but I'm learning.
>
OK, thanks, man. I thought you were going to revoke my privileges! ;>). Thanks for giving me a break. Any time you feel that I've crossed a line, please do let me know so we can openly discuss it and iron things out as professionals instead of letting any type of resentment grow.

> 
> Onwards with the show! ;)
>
I'll be appearing in and out around here as my current workload fluctuates due to the upcoming major s/w release due in December, plus some family gatherings coming up over the weekends. But yeah, onward and upward!!

**Comment by Firetop** [comment]
> > Buddy it's all good! I honestly figured thats what happened haha! ;) I didn't know what to do at the time, I should of remerged your changes into my dev the other way around, but I'm learning.
> 
> OK, thanks, man. I thought you were going to revoke my privileges! ;>). Thanks for giving me a break. Any time you feel that I've crossed a line, please do let me know so we can openly discuss it and iron things out as professionals instead of letting any type of resentment grow.
> 
> > Onwards with the show! ;)
> 

No lines crossed here! :) the goal is still the same which is have fun trying to figure this out.

I am honestly half to blame, I didn't say I made the dev branch, and I could of easily asked what to do in that situation, but I didn't and instead I kinda winged it lol!

If and when we ever get into a little mix up like that I'll make sure to just bring it up next time ahead of time so we can properly discuss it as you mentioned :)

> I'll be appearing in and out around here as my current workload fluctuates due to the upcoming major s/w release due in December, plus some family gatherings coming up over the weekends. But yeah, onward and upward!!

Perfect and no worries! it is the holidays after all!
Lifes been picking up for everyone! (Including myself) I'll probably be doing the same in and out updates over the next month!

Thanks again Martin, you da best.

**Pull request merged**
