### PR TITLE
Update MerlinAutoUpdate.sh

### PR DESCRIPTION
**Pull request by Martinski4GitHub**
Code improvements for getting the default USB mount point from possible multiple choices & setting the F/W Update log directory path.

### CODE REVIEW

**Review by Firetop — APPROVED** [review]

**Comment by Firetop** [comment]
@Martinski4GitHub 

Ugh duh, why the heck didn't I use FW_ZIP_DIR originally?
Obvious improvements here lol, I was getting tired by the end clearly.

Merged!

**Comment by Martinski4GitHub** [comment]
> @Martinski4GitHub
> 
> Updated our README.
> 
> Updated the script name too, and tided up a bit as the script is getting more and more mature. I rather it look clean as it gets more public facing.
> 
> I'll be working on the update checking tonight.. :)
>
Looking good!

**Comment by Martinski4GitHub** [comment]
> 
> I'll be working on the update checking tonight.. :)
>
With all the recent code changes & fixes that were made lately (and looks like more are coming soon), it might be a good idea to have 2 branches of the source code for purposes of managing & issuing releases.

The “**Main**” master release branch is generally the most stable, production-ready version that users can install or update to. Then the “**Test**” or “**Developer**” branch which has the most recent code changes but might not have yet been reviewed, verified, or fully tested so the code could be in the “Alpha” or “Beta” stage and not yet ready for production. Once tested & verified, the code in the “**Test**/**Developer**” branch gets merged into the stable “**Main**” master branch ready for new installs or updates by regular users.

Just my 2 cents.

**Comment by Firetop** [comment]
> > I'll be working on the update checking tonight.. :)
> 
> With all the recent code changes & fixes that were made lately (and looks like more are coming soon), it might be a good idea to have 2 branches of the source code for purposes of managing & issuing releases.
> 
> The “**Main**” master release branch is generally the most stable, production-ready version that users can install or update to. Then the “**Test**” or “**Developer**” branch which has the most recent code changes but might not have yet been reviewed, verified, or fully tested so the code could be in the “Alpha” or “Beta” stage and not yet ready for production. Once tested & verified, the code in the “**Test**/**Developer**” branch gets merged into the stable “**Main**” master branch ready for new installs or updates by regular users.
> 
> Just my 2 cents.

My friend, your 2 cents are more than valid. Esspecially considering I gave you author access to the project it's probably best we start to migrate away from making changes directly in the production script.

I won't lie I'm not very familar with the branches on github but it shouldn't be too hard to setup a "Test" or "Dev" branch.
Speaking of which, I have included Update checks of the script itself here:

https://github.com/Firetop/MerlinAutoUpdate-Router/commit/91128e3d99701578cfe49c9cd0f027902c7a957d

Assuming we move over to a new branch, and your okay with these changes, we may make this the first "master" release.
Else if you do notice anything worth changing, lets do it now so we have a stable base for "master" before going to dev/test

**Comment by Martinski4GitHub** [comment]
> 
> Assuming we move over to a new branch, and your okay with these changes, we may make this the first "master" release. Else if you do notice anything worth changing, lets do it now so we have a stable base for "master" before going to dev/test
>
I had only a very brief look at the new code, but I won't be able to run the latest version and check things out because I have relatives coming over for dinner this evening so I'm helping the Boss (aka wife :>) with cleaning and tidying up the house for guests.

Anyway, it may be a few days before I can come back to this because also this coming week I have a lot of work to do to complete my tasks for the last s/w release of this year due in mid-December.

**Comment by Firetop** [comment]
> > Assuming we move over to a new branch, and your okay with these changes, we may make this the first "master" release. Else if you do notice anything worth changing, lets do it now so we have a stable base for "master" before going to dev/test
> 
> I had only a very brief look at the new code, but I won't be able to run the latest version and check things out because I have relatives coming over for dinner this evening so I'm helping the Boss (aka wife :>) with cleaning and tidying up the house for guests.
> 
> Anyway, it may be a few days before I can come back to this because also this coming week I have a lot of work to do to complete my tasks for the last s/w release of this year due in mid-December.

No worries at all totally understand! My work is one of the reasons I paused for a few weeks while we were doing a release as well. (As well as the fact that I wanted to wait until an upcoming firmware release to properly test it)

Feel free to come back to it anytime, no pressure from me. I'll probably plug away at it here and there and see about making that dev branch so our work flow makes a little more sense.

Hopefully by the time you swing back around I'll have made some progress!

**Comment by Firetop** [comment]
Also, just wanted to say it's been fun trying to start a new project on my spare time, and something as ambitious as this, it's been nice to have some support from someone else.

I still know many people may not want to use this, but still not a reason to not explore it and make it as reliable as possible. I know some people like the project and I'm happy I found someone such as yourself to go down the rabbit hole with!

**Pull request merged**
